export const ORDER_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const ORDER_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const ORDER_DELIVERED_REQUEST = 'PRODUCT_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'PRODUCT_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAIL = 'PRODUCT_DELIVERED_FAIL'
export const ORDER_DELIVERED_RESET = 'PRODUCT_DELIVERED_RESET'